// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Sessions struct {
	ID        string        `json:"id"`
	UserID    sql.NullInt32 `json:"user_id"`
	CreatedAt sql.NullTime  `json:"created_at"`
	ExpiresAt time.Time     `json:"expires_at"`
}

type Users struct {
	ID           int32        `json:"id"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}
