package animals

type Animal struct {
	Species string
	Meaning string
}

var Animals = []Animal{
	{Species: "Ant", Meaning: "Teamwork, discipline, endurance, patience"},
	{Species: "Bat", Meaning: "Rebirth, intuition, facing fears, letting go"},
	{Species: "Bear", Meaning: "Authority, bravery, alchemy, motherhood"},
	{Species: "Bee", Meaning: "Hard work, communication, community"},
	{Species: "Boar", Meaning: "Bravery, determination, protection, wild spirit"},
	{Species: "Butterfly", Meaning: "Metamorphosis, rebirth, soul"},
	{Species: "Camel", Meaning: "Endurance, resilience, survival, patience"},
	{Species: "Cat", Meaning: "Magic, mystery, protection, intuition"},
	{Species: "Cheetah", Meaning: "Speed, focus, agility, decisiveness"},
	{Species: "Chameleon", Meaning: "Adaptability, perception, sensitivity, camouflage"},
	{Species: "Crab", Meaning: "Cycles, emotion, protection, intuition"},
	{Species: "Crow", Meaning: "Transformation, prophecy, death, magic"},
	{Species: "Deer", Meaning: "Gentleness, spiritual awareness, healing"},
	{Species: "Dog", Meaning: "Loyalty, protection, companionship"},
	{Species: "Dolphin", Meaning: "Kindness, communication, guidance"},
	{Species: "Dragon", Meaning: "Power, magic, transformation, wisdom"},
	{Species: "Eagle", Meaning: "Vision, clarity, divine spirit"},
	{Species: "Elephant", Meaning: "Memory, strength, wisdom, ancestral knowledge"},
	{Species: "Flamingo", Meaning: "Balance, beauty, vibrant expression, community"},
	{Species: "Fox", Meaning: "Cunning, adaptability, wisdom, trickster"},
	{Species: "Frog", Meaning: "Cleansing, renewal, emotional healing"},
	{Species: "Gazelle", Meaning: "Grace, agility, alertness, awareness"},
	{Species: "Goat", Meaning: "Tenacity, ambition, surefootedness, resilience"},
	{Species: "Horse", Meaning: "Stamina, freedom, prophecy"},
	{Species: "Kangaroo", Meaning: "Progress, nurturing, momentum, maternal energy"},
	{Species: "Koala", Meaning: "Calm, trust, innocence, emotional healing"},
	{Species: "Lion", Meaning: "Power, courage, nobility"},
	{Species: "Lizard", Meaning: "Dreaming, adaptability, survival"},
	{Species: "Monkey", Meaning: "Playfulness, curiosity, intelligence, mischief"},
	{Species: "Moose", Meaning: "Self-esteem, strength, courage, independence"},
	{Species: "Octopus", Meaning: "Flexibility, intelligence, mystery, illusion"},
	{Species: "Owl", Meaning: "Wisdom, hidden knowledge, death, divination"},
	{Species: "Panther", Meaning: "Stealth, healing, darkness, hidden truth"},
	{Species: "Parrot", Meaning: "Communication, color, playfulness, mimicry"},
	{Species: "Peacock", Meaning: "Beauty, resurrection, confidence, integrity"},
	{Species: "Penguin", Meaning: "Adaptability, unity, balance, endurance"},
	{Species: "Porcupine", Meaning: "Innocence, boundaries, protection, trust"},
	{Species: "Rabbit", Meaning: "Rebirth, intuition, fertility"},
	{Species: "Raccoon", Meaning: "Curiosity, cleverness, resourcefulness, disguise"},
	{Species: "Ram", Meaning: "Drive, leadership, initiative, assertiveness"},
	{Species: "Seahorse", Meaning: "Patience, perspective, protection, calmness"},
	{Species: "Snake", Meaning: "Rebirth, healing, wisdom, transformation"},
	{Species: "Spider", Meaning: "Creativity, fate, weaving destiny"},
	{Species: "Stag", Meaning: "Masculinity, leadership, protection"},
	{Species: "Swan", Meaning: "Grace, transformation, inner beauty, soul mate connection"},
	{Species: "Tiger", Meaning: "Passion, unpredictability, sensuality, raw power"},
	{Species: "Turkey", Meaning: "Generosity, gratitude, sacrifice, abundance"},
	{Species: "Turtle", Meaning: "Longevity, grounding, patience, the Earth"},
	{Species: "Whale", Meaning: "Emotional depth, communication, ancient wisdom"},
	{Species: "Wolf", Meaning: "Strength, loyalty, guidance, courage"},
}
